#pragma once

#include "core/scheduler/flow_scheduler.hpp"
#include "core/scheduler/imix_engine.hpp"
#include "core/stats/metrics_collector.hpp"
#include "core/common/types.hpp"
#include <grpcpp/grpcpp.h>
#include <memory>
#include <mutex>
#include <string>

// Include generated proto headers (these will be generated by cmake)
// Proto files are generated in ${CMAKE_BINARY_DIR}/proto/ directory
// Package name is "trafficgen", so classes are in trafficgen namespace
// Note: Include paths are set in CMakeLists.txt
#include "traffic_generator.grpc.pb.h"
#include "traffic_generator.pb.h"

namespace trafficgen {

/**
 * gRPC service implementation for traffic generator control plane
 */
class TrafficGeneratorServiceImpl final : public TrafficGeneratorService::Service {
public:
    TrafficGeneratorServiceImpl(
        std::shared_ptr<FlowScheduler> flow_scheduler,
        std::shared_ptr<IMIXEngine> imix_engine,
        std::shared_ptr<MetricsCollector> metrics_collector);
    
    ~TrafficGeneratorServiceImpl();
    
    // gRPC service methods
    grpc::Status ConfigureIMIX(grpc::ServerContext* context,
                               const IMIXConfig* request,
                               StatusResponse* response) override;
    
    grpc::Status ConfigureFlows(grpc::ServerContext* context,
                                const FlowConfig* request,
                                StatusResponse* response) override;
    
    grpc::Status StartTraffic(grpc::ServerContext* context,
                              const StartRequest* request,
                              StatusResponse* response) override;
    
    grpc::Status StopTraffic(grpc::ServerContext* context,
                             const StopRequest* request,
                             StatusResponse* response) override;
    
    grpc::Status GetMetrics(grpc::ServerContext* context,
                            const MetricsRequest* request,
                            MetricsResponse* response) override;
    
    grpc::Status GetStats(grpc::ServerContext* context,
                          const StatsRequest* request,
                          StatsResponse* response) override;

private:
    std::shared_ptr<FlowScheduler> flow_scheduler_;
    std::shared_ptr<IMIXEngine> imix_engine_;
    std::shared_ptr<MetricsCollector> metrics_collector_;
    mutable std::mutex mutex_;
    
    // Helper methods
    FlowKey convert_proto_flow_key(const Flow& flow);
    IMIXEntry convert_proto_imix_entry(const IMIXEntry& entry);
};

/**
 * gRPC server wrapper
 */
class GRPCServer {
public:
    GRPCServer();
    ~GRPCServer();
    
    // Initialize server with components
    bool initialize(
        const std::string& listen_address,
        uint16_t port,
        std::shared_ptr<FlowScheduler> flow_scheduler,
        std::shared_ptr<IMIXEngine> imix_engine,
        std::shared_ptr<MetricsCollector> metrics_collector);
    
    // Start server
    bool start();
    
    // Stop server
    void stop();
    
    // Wait for server to finish
    void wait();
    
    // Check if server is running
    bool is_running() const;

private:
    std::unique_ptr<grpc::Server> server_;
    std::unique_ptr<TrafficGeneratorServiceImpl> service_;
    std::string server_address_;
    std::mutex mutex_;
    bool running_;
};

} // namespace trafficgen

